import {copyFile, mkdir, writeFile} from 'node:fs/promises';
import {join} from 'node:path';

const sampleRate = 22050;
const output = new URL('../public/audio/', import.meta.url).pathname;
const publicDirectory = new URL('../public/', import.meta.url).pathname;
const repositoryLogo = new URL('../../vinglish-zero.svg', import.meta.url);

const clamp = (value) => Math.max(-1, Math.min(1, value));

const writeWav = async (name, samples) => {
  const dataSize = samples.length * 2;
  const buffer = Buffer.alloc(44 + dataSize);
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(1, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(sampleRate * 2, 28);
  buffer.writeUInt16LE(2, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);
  samples.forEach((sample, index) => buffer.writeInt16LE(Math.round(clamp(sample) * 32767), 44 + index * 2));
  await writeFile(join(output, name), buffer);
};

const tone = (seconds, generator) => {
  const samples = new Float32Array(Math.ceil(seconds * sampleRate));
  for (let index = 0; index < samples.length; index += 1) {
    samples[index] = generator(index / sampleRate, index, samples.length);
  }
  return samples;
};

const envelope = (time, duration, attack = 0.01, release = 0.08) => {
  if (time < attack) return time / attack;
  if (time > duration - release) return Math.max(0, (duration - time) / release);
  return 1;
};

const seededNoise = (seed) => {
  let value = seed;
  return () => {
    value = (value * 1664525 + 1013904223) >>> 0;
    return value / 0xffffffff * 2 - 1;
  };
};

await mkdir(output, {recursive: true});
await copyFile(repositoryLogo, join(publicDirectory, 'vinglish-zero.svg'));

const ambientNoise = seededNoise(41);
await writeWav('ambient.wav', tone(180, (time) => {
  const movement = 0.5 + 0.5 * Math.sin(time * 0.12);
  const drone = Math.sin(time * Math.PI * 2 * 48) * 0.028 + Math.sin(time * Math.PI * 2 * 72) * 0.018;
  const shimmer = Math.sin(time * Math.PI * 2 * (179 + Math.sin(time * 0.07) * 9)) * 0.003;
  return drone * (0.55 + movement * 0.45) + shimmer + ambientNoise() * 0.0025;
}));

await writeWav('click.wav', tone(0.22, (time) => {
  const sweep = 1200 - time * 3000;
  return Math.sin(time * Math.PI * 2 * Math.max(180, sweep)) * envelope(time, 0.22, 0.002, 0.16) * 0.27;
}));

await writeWav('pulse.wav', tone(0.62, (time) => {
  const carrier = Math.sin(time * Math.PI * 2 * (180 + time * 420));
  const harmonic = Math.sin(time * Math.PI * 2 * (360 + time * 760)) * 0.32;
  return (carrier + harmonic) * envelope(time, 0.62, 0.01, 0.42) * 0.17;
}));

await writeWav('rise.wav', tone(1.48, (time) => {
  const frequency = 135 * Math.pow(6.4, time / 1.48);
  return Math.sin(time * Math.PI * 2 * frequency) * envelope(time, 1.48, 0.08, 0.4) * 0.16;
}));

await writeWav('error.wav', tone(0.7, (time) => {
  const wobble = Math.sin(time * Math.PI * 2 * 7) * 8;
  const signal = Math.sin(time * Math.PI * 2 * (155 + wobble)) + Math.sin(time * Math.PI * 2 * (205 - wobble)) * 0.45;
  return signal * envelope(time, 0.7, 0.01, 0.35) * 0.17;
}));

for (let index = 1; index <= 9; index += 1) {
  const filename = `narration-${String(index).padStart(2, '0')}.wav`;
  await writeWav(filename, tone(0.12, () => 0));
}

await writeFile(join(output, '.generated'), 'Generated by scripts/generate-audio.mjs\n');
