//! Reproducible, documentation-only capture of the current semantic pipeline.
//!
//! This example intentionally calls only the public adapter, facts, reasoning,
//! and diagnostics APIs. It does not add rules or modify any production crate.

use std::{
    fs,
    path::{Path, PathBuf},
    time::Instant,
};

use serde::Serialize;
use serde_json::{json, Value};
use vz_adapter_python::PythonAdapter;
use vz_adapter_vinglish::VinglishAdapter;
use vz_diagnostics::{CompilerDiagnostic, DiagnosticCategory, SemanticDiagnosticEngine, Severity};
use vz_reasoning::{
    report::{HypothesisReport, HypothesisStatus, IntentReport},
    FactExtractor, ReasoningEngine,
};
use vz_semantic_ir::SemanticGraph;

const ROOT: &str = env!("CARGO_MANIFEST_DIR");
const DETERMINISM_RUNS: usize = 5;

#[derive(Clone, Copy)]
struct ShowcaseCase {
    id: &'static str,
    title: &'static str,
    category: &'static str,
    source: &'static str,
    diagnostic: Option<DiagnosticSpec>,
    repeat: bool,
}

#[derive(Clone, Copy)]
struct DiagnosticSpec {
    code: &'static str,
    category: DiagnosticCategoryTag,
    message: &'static str,
}

#[derive(Clone, Copy)]
enum DiagnosticCategoryTag {
    TypeMismatch,
    MissingDivision,
    MoveAfterUse,
}

impl DiagnosticCategoryTag {
    fn value(self) -> DiagnosticCategory {
        match self {
            Self::TypeMismatch => DiagnosticCategory::TypeMismatch,
            Self::MissingDivision => DiagnosticCategory::MissingDivision,
            Self::MoveAfterUse => DiagnosticCategory::MoveAfterUse,
        }
    }
}

#[derive(Serialize)]
struct CaseIndex {
    id: String,
    title: String,
    category: String,
    language: String,
    status: String,
    function_count: usize,
    facts: usize,
    evidence: usize,
    hypotheses: usize,
    active_hypotheses: usize,
    eliminated_hypotheses: usize,
    diagnostics_generated: bool,
    timing: Timing,
}

#[derive(Default, Clone, Serialize)]
struct Timing {
    adapter_micros: u128,
    reasoning_micros: u128,
    diagnostics_micros: Option<u128>,
}

macro_rules! case {
    ($id:literal, $title:literal, $category:literal, $source:expr) => {
        ShowcaseCase {
            id: $id,
            title: $title,
            category: $category,
            source: $source,
            diagnostic: None,
            repeat: matches!(
                $id,
                "arithmetic" | "counter" | "filter" | "nested_loops" | "pattern_matching"
            ),
        }
    };
}

macro_rules! case_diag {
    ($id:literal, $title:literal, $category:literal, $source:expr, $code:literal, $diagnostic_category:ident, $message:literal) => {
        ShowcaseCase {
            id: $id,
            title: $title,
            category: $category,
            source: $source,
            diagnostic: Some(DiagnosticSpec {
                code: $code,
                category: DiagnosticCategoryTag::$diagnostic_category,
                message: $message,
            }),
            repeat: true,
        }
    };
}

#[derive(Default)]
struct Totals {
    analyzed: usize,
    adapter_micros: u128,
    reasoning_micros: u128,
    diagnostics_micros: u128,
    diagnostics_count: usize,
    largest_case: String,
    largest_ir_bytes: u64,
    most_evidence_case: String,
    most_evidence: usize,
    most_hypotheses_case: String,
    most_hypotheses: usize,
    confidence_sum: u64,
    confidence_count: usize,
    active: usize,
    eliminated: usize,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(ROOT).join("../..");
    let gallery = root.join("gallery");
    reset_generated_gallery(&gallery)?;

    let cases = showcase_cases();
    let mut entries = Vec::new();
    let mut totals = Totals::default();
    for case in cases {
        entries.push(capture_python_case(&root, &gallery, case, &mut totals)?);
    }
    entries.push(capture_vinglish_case(&root, &gallery, &mut totals)?);

    write_json(&gallery.join("index.json"), &entries)?;
    write_json(&gallery.join("statistics.json"), &statistics(&totals))?;
    write_text(
        &gallery.join("README.md"),
        "# Generated Showcase Artifacts\n\nThis directory is generated by `cargo run -p vz-adapter-python --example showcase`. Each case contains only outputs captured from the current public pipeline. `semantic-ir.debug.txt` is the adapter-produced graph debug representation; all JSON files are direct serializations or deterministic projections of public output types.\n",
    )?;
    Ok(())
}

fn capture_python_case(
    root: &Path,
    gallery: &Path,
    case: ShowcaseCase,
    totals: &mut Totals,
) -> Result<CaseIndex, Box<dyn std::error::Error>> {
    let directory = gallery.join(case.id);
    fs::create_dir_all(&directory)?;
    let source_path = root
        .join("examples/showcase")
        .join(format!("{}.py", case.id));
    write_text(&source_path, case.source)?;
    write_text(&directory.join("source.py"), case.source)?;

    let adapter_started = Instant::now();
    let graph = PythonAdapter::default().from_source(format!("{}.py", case.id), case.source);
    let adapter_micros = adapter_started.elapsed().as_micros();
    match graph {
        Ok(graph) => capture_graph_case(
            &directory,
            case.id,
            case.title,
            case.category,
            "python",
            graph,
            case.diagnostic,
            case.repeat,
            Timing {
                adapter_micros,
                ..Timing::default()
            },
            totals,
        ),
        Err(error) => {
            write_text(&directory.join("adapter-error.txt"), &format!("{error}\n"))?;
            write_json(
                &directory.join("summary.json"),
                &json!({
                    "status": "adapter_error",
                    "stage": "python_ast_parse",
                    "error": error.to_string(),
                    "adapter_micros": adapter_micros,
                    "semantic_ir_generated": false,
                }),
            )?;
            Ok(CaseIndex {
                id: case.id.to_owned(),
                title: case.title.to_owned(),
                category: case.category.to_owned(),
                language: "python".to_owned(),
                status: "adapter_error".to_owned(),
                function_count: 0,
                facts: 0,
                evidence: 0,
                hypotheses: 0,
                active_hypotheses: 0,
                eliminated_hypotheses: 0,
                diagnostics_generated: false,
                timing: Timing {
                    adapter_micros,
                    ..Timing::default()
                },
            })
        }
    }
}

fn capture_vinglish_case(
    root: &Path,
    gallery: &Path,
    totals: &mut Totals,
) -> Result<CaseIndex, Box<dyn std::error::Error>> {
    let id = "cross_language_vinglish_accumulator";
    let directory = gallery.join(id);
    fs::create_dir_all(&directory)?;
    let transport = fs::read_to_string(root.join("tests/fixtures/accumulate-v1.json"))?;
    write_text(&directory.join("transport.json"), &transport)?;
    let started = Instant::now();
    let graph = VinglishAdapter::default().import_json(&transport)?;
    capture_graph_case(
        &directory,
        id,
        "Vinglish transport accumulator",
        "cross-language",
        "vinglish_transport_v1",
        graph,
        None,
        true,
        Timing {
            adapter_micros: started.elapsed().as_micros(),
            ..Timing::default()
        },
        totals,
    )
}

#[allow(clippy::too_many_arguments)]
fn capture_graph_case(
    directory: &Path,
    id: &str,
    title: &str,
    category: &str,
    language: &str,
    graph: SemanticGraph,
    diagnostic: Option<DiagnosticSpec>,
    repeat: bool,
    mut timing: Timing,
    totals: &mut Totals,
) -> Result<CaseIndex, Box<dyn std::error::Error>> {
    let ir_debug = format!("{graph:#?}\n");
    write_text(&directory.join("semantic-ir.debug.txt"), &ir_debug)?;
    let facts = FactExtractor.extract(&graph);
    write_json(&directory.join("facts.json"), &facts)?;

    let engine = ReasoningEngine::new();
    let reasoning_started = Instant::now();
    let report = engine.analyze(&graph);
    timing.reasoning_micros = reasoning_started.elapsed().as_micros();
    write_json(&directory.join("intent-report.json"), &report)?;
    write_report_projections(directory, &report)?;

    let semantic_diagnostic = diagnostic
        .map(|spec| {
            let compiler_diagnostic = CompilerDiagnostic {
                code: spec.code.to_owned(),
                severity: Severity::Error,
                category: spec.category.value(),
                message: spec.message.to_owned(),
                location: None,
                function_name: report
                    .function_reports
                    .first()
                    .map(|function| function.function_name.clone()),
            };
            let started = Instant::now();
            let output = SemanticDiagnosticEngine::new().diagnose(compiler_diagnostic, &report);
            timing.diagnostics_micros = Some(started.elapsed().as_micros());
            output
        })
        .transpose()?;
    if let Some(output) = &semantic_diagnostic {
        write_json(&directory.join("semantic-diagnostic.json"), output)?;
        write_json(
            &directory.join("compiler-diagnostic.json"),
            &output.compiler_issue,
        )?;
        write_json(&directory.join("suggested-fixes.json"), &output.suggestions)?;
        write_text(
            &directory.join("error-gallery-card.txt"),
            &error_gallery_card(&report, output),
        )?;
    } else {
        write_json(&directory.join("semantic-diagnostic.json"), &Value::Null)?;
        write_json(
            &directory.join("suggested-fixes.json"),
            &Vec::<Value>::new(),
        )?;
    }
    if repeat {
        write_json(
            &directory.join("determinism.json"),
            &verify_determinism(&graph, diagnostic, DETERMINISM_RUNS)?,
        )?;
    }

    let hypotheses: Vec<&HypothesisReport> = report
        .function_reports
        .iter()
        .flat_map(|function| function.hypotheses.iter())
        .collect();
    let evidence = report
        .function_reports
        .iter()
        .map(|function| function.evidence.len())
        .sum::<usize>();
    let active = hypotheses
        .iter()
        .filter(|hypothesis| hypothesis.status == HypothesisStatus::Active)
        .count();
    let eliminated = hypotheses.len() - active;
    let ir_bytes = ir_debug.len() as u64;
    totals.analyzed += 1;
    totals.adapter_micros += timing.adapter_micros;
    totals.reasoning_micros += timing.reasoning_micros;
    if let Some(duration) = timing.diagnostics_micros {
        totals.diagnostics_count += 1;
        totals.diagnostics_micros += duration;
    }
    totals.active += active;
    totals.eliminated += eliminated;
    totals.confidence_sum += hypotheses
        .iter()
        .map(|hypothesis| hypothesis.confidence as u64)
        .sum::<u64>();
    totals.confidence_count += hypotheses.len();
    if ir_bytes > totals.largest_ir_bytes {
        totals.largest_ir_bytes = ir_bytes;
        totals.largest_case = id.to_owned();
    }
    if evidence > totals.most_evidence {
        totals.most_evidence = evidence;
        totals.most_evidence_case = id.to_owned();
    }
    if hypotheses.len() > totals.most_hypotheses {
        totals.most_hypotheses = hypotheses.len();
        totals.most_hypotheses_case = id.to_owned();
    }

    let index = CaseIndex {
        id: id.to_owned(),
        title: title.to_owned(),
        category: category.to_owned(),
        language: language.to_owned(),
        status: "analyzed".to_owned(),
        function_count: facts.function_count as usize,
        facts: facts.functions.len(),
        evidence,
        hypotheses: hypotheses.len(),
        active_hypotheses: active,
        eliminated_hypotheses: eliminated,
        diagnostics_generated: semantic_diagnostic.is_some(),
        timing,
    };
    write_json(&directory.join("summary.json"), &index)?;
    Ok(index)
}

fn error_gallery_card(
    report: &IntentReport,
    diagnostic: &vz_diagnostics::SemanticDiagnostic,
) -> String {
    let mut result = String::new();
    result.push_str("Compiler diagnostic\n");
    result.push_str(&format!(
        "  code: {}\n  severity: {:?}\n  category: {:?}\n  message: {}\n",
        diagnostic.compiler_issue.code,
        diagnostic.compiler_issue.severity,
        diagnostic.compiler_issue.category,
        diagnostic.compiler_issue.message
    ));
    result.push_str("\nSemantic diagnostic\n");
    result.push_str(&format!(
        "  interpretation: {:?}\n",
        diagnostic.interpretation
    ));
    if let Some(intent) = &diagnostic.intent {
        result.push_str(&format!(
            "  intent: {}\n  confidence: {}\n  evidence:\n",
            intent.hypothesis_id, intent.confidence
        ));
        for evidence in &intent.evidence {
            result.push_str(&format!(
                "    - {} x{}\n",
                serde_json::to_string(&evidence.kind).unwrap(),
                evidence.strength
            ));
        }
    } else {
        result.push_str("  intent: none\n  confidence: n/a\n  evidence: none\n");
    }
    result.push_str("\nSuggested fixes\n");
    if diagnostic.suggestions.is_empty() {
        result.push_str("  none\n");
    } else {
        for suggestion in &diagnostic.suggestions {
            result.push_str(&format!(
                "  - {:?}; {:?}; {:?}; confidence {}\n",
                suggestion.title,
                suggestion.explanation,
                suggestion.rationale,
                suggestion.confidence
            ));
        }
    }
    result.push_str("\nRejected hypotheses\n");
    for function in &report.function_reports {
        for hypothesis in &function.hypotheses {
            if hypothesis.status == HypothesisStatus::Eliminated {
                let reasons = hypothesis
                    .rejected_evidence
                    .iter()
                    .map(|rejection| serde_json::to_string(rejection).unwrap())
                    .collect::<Vec<_>>()
                    .join("; ");
                result.push_str(&format!("  - {}: {}\n", hypothesis.id, reasons));
            }
        }
    }
    result
}

fn write_report_projections(
    directory: &Path,
    report: &IntentReport,
) -> Result<(), Box<dyn std::error::Error>> {
    let evidence: Vec<_> = report
        .function_reports
        .iter()
        .map(|function| json!({ "function_name": function.function_name, "evidence": function.evidence }))
        .collect();
    let candidates: Vec<_> = report
        .function_reports
        .iter()
        .map(|function| json!({ "function_name": function.function_name, "hypotheses": function.hypotheses }))
        .collect();
    let eliminations: Vec<_> = report
        .function_reports
        .iter()
        .map(|function| json!({
            "function_name": function.function_name,
            "eliminated": function.hypotheses.iter().filter(|hypothesis| hypothesis.status == HypothesisStatus::Eliminated).collect::<Vec<_>>(),
        }))
        .collect();
    let remaining: Vec<_> = report
        .function_reports
        .iter()
        .map(|function| json!({
            "function_name": function.function_name,
            "active": function.hypotheses.iter().filter(|hypothesis| hypothesis.status == HypothesisStatus::Active).collect::<Vec<_>>(),
        }))
        .collect();
    let confidence: Vec<_> = report
        .function_reports
        .iter()
        .map(|function| {
            json!({
                "function_name": function.function_name,
                "scores": function.hypotheses.iter().map(|hypothesis| json!({
                    "id": hypothesis.id,
                    "confidence": hypothesis.confidence,
                    "status": hypothesis.status,
                })).collect::<Vec<_>>(),
            })
        })
        .collect();

    write_json(&directory.join("evidence.json"), &evidence)?;
    write_json(&directory.join("candidate-hypotheses.json"), &candidates)?;
    write_json(
        &directory.join("constraint-eliminations.json"),
        &eliminations,
    )?;
    write_json(&directory.join("remaining-hypotheses.json"), &remaining)?;
    write_json(&directory.join("confidence-scores.json"), &confidence)?;
    write_text(
        &directory.join("rejection-rationale.md"),
        &rejection_rationale(report),
    )?;
    Ok(())
}

fn rejection_rationale(report: &IntentReport) -> String {
    let mut result = String::from("# Constraint Outcomes\n\nThis file is a direct rendering of `rejected_evidence`; no additional interpretation is added.\n");
    for function in &report.function_reports {
        result.push_str(&format!("\n## {}\n", function.function_name));
        for hypothesis in &function.hypotheses {
            if hypothesis.rejected_evidence.is_empty() {
                continue;
            }
            result.push_str(&format!("\n### {}\n\n", hypothesis.id));
            for rejection in &hypothesis.rejected_evidence {
                result.push_str(&format!(
                    "- `{}`\n",
                    serde_json::to_string(rejection).unwrap()
                ));
            }
        }
    }
    result
}

fn verify_determinism(
    graph: &SemanticGraph,
    diagnostic: Option<DiagnosticSpec>,
    runs: usize,
) -> Result<Value, Box<dyn std::error::Error>> {
    let mut report_bytes = None;
    let mut diagnostic_bytes = None;
    for _ in 0..runs {
        let report = ReasoningEngine::new().analyze(graph);
        let current_report = serde_json::to_vec(&report)?;
        if let Some(expected) = &report_bytes {
            assert_eq!(
                expected, &current_report,
                "intent reports must be byte-identical"
            );
        } else {
            report_bytes = Some(current_report);
        }
        if let Some(spec) = diagnostic {
            let compiler_diagnostic = CompilerDiagnostic {
                code: spec.code.to_owned(),
                severity: Severity::Error,
                category: spec.category.value(),
                message: spec.message.to_owned(),
                location: None,
                function_name: report
                    .function_reports
                    .first()
                    .map(|function| function.function_name.clone()),
            };
            let output = SemanticDiagnosticEngine::new().diagnose(compiler_diagnostic, &report)?;
            let current_diagnostic = serde_json::to_vec(&output)?;
            if let Some(expected) = &diagnostic_bytes {
                assert_eq!(
                    expected, &current_diagnostic,
                    "semantic diagnostics must be byte-identical"
                );
            } else {
                diagnostic_bytes = Some(current_diagnostic);
            }
        }
    }
    Ok(json!({
        "runs": runs,
        "intent_report_byte_identical": true,
        "semantic_diagnostic_byte_identical": diagnostic.is_some(),
    }))
}

fn statistics(totals: &Totals) -> Value {
    let average = |sum: u128, count: usize| {
        if count == 0 {
            0.0
        } else {
            sum as f64 / count as f64
        }
    };
    json!({
        "analyzed_examples": totals.analyzed,
        "average_adapter_micros": average(totals.adapter_micros, totals.analyzed),
        "average_reasoning_micros": average(totals.reasoning_micros, totals.analyzed),
        "average_diagnostics_micros": average(totals.diagnostics_micros, totals.diagnostics_count),
        "largest_example": { "id": totals.largest_case, "semantic_ir_debug_bytes": totals.largest_ir_bytes },
        "most_evidence": { "id": totals.most_evidence_case, "count": totals.most_evidence },
        "most_hypotheses_considered": { "id": totals.most_hypotheses_case, "count": totals.most_hypotheses },
        "average_confidence_across_all_candidates": if totals.confidence_count == 0 { 0.0 } else { totals.confidence_sum as f64 / totals.confidence_count as f64 },
        "hypothesis_status_distribution": { "active": totals.active, "eliminated": totals.eliminated },
        "measurement_note": "Microsecond wall-clock timings are a single local capture, not a benchmark."
    })
}

fn reset_generated_gallery(gallery: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if gallery.exists() {
        fs::remove_dir_all(gallery)?;
    }
    fs::create_dir_all(gallery)?;
    Ok(())
}

fn write_json(path: &Path, value: &impl Serialize) -> Result<(), Box<dyn std::error::Error>> {
    write_text(path, &format!("{}\n", serde_json::to_string_pretty(value)?))
}

fn write_text(path: &Path, contents: &str) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(())
}

fn showcase_cases() -> Vec<ShowcaseCase> {
    vec![
        case!(
            "arithmetic",
            "Arithmetic",
            "arithmetic",
            r#"def arithmetic(left: int, right: int) -> int:
    return left + right * 2
"#
        ),
        case_diag!(
            "accumulator",
            "Accumulator with type mismatch",
            "accumulator",
            r#"def calculate(numbers: list[int]) -> int:
    total = 0
    for number in numbers:
        total += number
    return total
"#,
            "PY-ACC-001",
            TypeMismatch,
            "unsupported operand types for +="
        ),
        case!(
            "counter",
            "Counter",
            "counter",
            r#"def count_items(items: list[int]) -> int:
    count = 0
    for item in items:
        count += 1
    return count
"#
        ),
        case!(
            "average",
            "Average",
            "average",
            r#"def average(numbers: list[int]) -> float:
    total = 0
    count = 0
    for number in numbers:
        total += number
        count += 1
    return total / count
"#
        ),
        case_diag!(
            "missing_division",
            "Average missing division",
            "invalid implementation",
            r#"def average(numbers: list[int]) -> float:
    total = 0
    for number in numbers:
        total += number
    return total
"#,
            "PY-AVG-001",
            MissingDivision,
            "average computation has no division step"
        ),
        case!(
            "reducer",
            "Reducer",
            "reducer",
            r#"def reduce_values(values: list[int]) -> int:
    result = 0
    for value in values:
        result += value
    return result
"#
        ),
        case!(
            "mapper",
            "Mapper",
            "mapper",
            r#"def map_values(values: list[int]) -> list[int]:
    for value in values:
        emit(transform(value))
"#
        ),
        case!(
            "filter",
            "Filter",
            "filter",
            r#"def filter_positive(values: list[int]) -> list[int]:
    for value in values:
        if value > 0:
            emit(value)
"#
        ),
        case!(
            "validator",
            "Validator",
            "validator",
            r#"def validate(value: int) -> bool:
    if value < 0:
        return False
    return True
"#
        ),
        case!(
            "parser",
            "Parser-like conditional",
            "parser",
            r#"def parse_value(text: str) -> bool:
    if accepts(text):
        return True
    return False
"#
        ),
        case!(
            "state_machine",
            "State machine",
            "state machine",
            r#"def advance_state(events: list[int]) -> int:
    state = 0
    for event in events:
        if event > 0:
            state += 1
    return state
"#
        ),
        case_diag!(
            "ownership",
            "Ownership-style call sequence",
            "ownership",
            r#"def use_after_transfer(resource: int) -> int:
    transfer(resource)
    return resource
"#,
            "PY-OWN-001",
            MoveAfterUse,
            "value used after transfer"
        ),
        case!(
            "mutation",
            "Mutation without a loop",
            "mutation",
            r#"def mutate(value: int) -> int:
    value += 1
    return value
"#
        ),
        case!(
            "nested_loops",
            "Nested loops",
            "nested loops",
            r#"def pair_sum(rows: list[int]) -> int:
    total = 0
    for row in rows:
        for value in rows:
            total += value
    return total
"#
        ),
        case!(
            "nested_conditionals",
            "Nested conditionals",
            "nested conditionals",
            r#"def classify(value: int) -> bool:
    if value > 0:
        if value < 10:
            return True
    return False
"#
        ),
        case!(
            "early_return",
            "Early return search",
            "early returns",
            r#"def find_positive(values: list[int]) -> int:
    for value in values:
        if value > 0:
            return value
    return 0
"#
        ),
        case!(
            "collections",
            "Collection literal and iteration",
            "collections",
            r#"def inspect(values: list[int]) -> int:
    defaults = [1, 2, 3]
    for value in values:
        emit(value)
    return 0
"#
        ),
        case!(
            "recursion",
            "Recursion",
            "recursion",
            r#"def descend(value: int) -> int:
    if value <= 0:
        return 0
    return descend(value - 1)
"#
        ),
        case!(
            "composition",
            "Function composition",
            "function composition",
            r#"def compose(value: int) -> int:
    return outer(inner(value))
"#
        ),
        case!(
            "pattern_matching",
            "Python pattern matching",
            "unsupported construct",
            r#"def classify(value: int) -> int:
    match value:
        case 0:
            return 0
        case _:
            return 1
"#
        ),
        case!(
            "resource_management",
            "Resource-management style calls",
            "resource management",
            r#"def manage(resource: int) -> int:
    allocate(resource)
    release(resource)
    return resource
"#
        ),
        case_diag!(
            "wrong_return_type",
            "Wrong return type",
            "invalid implementation",
            r#"def format_total(values: list[int]) -> str:
    total = 0
    for value in values:
        total += value
    return total
"#,
            "PY-RET-001",
            TypeMismatch,
            "declared return type is incompatible with returned value"
        ),
        case_diag!(
            "incorrect_accumulator",
            "Incorrect accumulator",
            "invalid implementation",
            r#"def calculate(numbers: list[int]) -> int:
    total = 0
    for number in numbers:
        total += number
    return total
"#,
            "PY-ACC-002",
            TypeMismatch,
            "accumulator and incoming value are incompatible"
        ),
        case!(
            "unsupported_with",
            "Unsupported with statement",
            "unsupported construct",
            r#"def read_resource(resource: int) -> int:
    with resource:
        return resource
"#
        ),
        case!(
            "while_loop",
            "While loop",
            "edge case",
            r#"def countdown(value: int) -> int:
    while value > 0:
        value -= 1
    return value
"#
        ),
        case!(
            "empty_function",
            "Empty function",
            "edge case",
            r#"def empty() -> None:
    pass
"#
        ),
        case!(
            "malformed_input",
            "Malformed Python input",
            "malformed input",
            r#"def broken(:
    return 1
"#
        ),
    ]
}
